// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ1B29IQ_d7KNKdicrCHUxvFklvkl_Vp0',
    appId: '1:1009942668656:web:0aba017fcc82b29bb55bb5',
    messagingSenderId: '1009942668656',
    projectId: 'olopsc-thesis',
    authDomain: 'olopsc-thesis.firebaseapp.com',
    storageBucket: 'olopsc-thesis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM8ovD-x3633y_PYWpmn6f8BSwdaVyf7w',
    appId: '1:1009942668656:android:1e4d953cebd5ae63b55bb5',
    messagingSenderId: '1009942668656',
    projectId: 'olopsc-thesis',
    storageBucket: 'olopsc-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHhf_zyia4mnUJ2q7GlUSjvAGR_wkayU',
    appId: '1:1009942668656:ios:320253a70c43e3a6b55bb5',
    messagingSenderId: '1009942668656',
    projectId: 'olopsc-thesis',
    storageBucket: 'olopsc-thesis.appspot.com',
    iosClientId: '1009942668656-pbip40b2nps7erhh2bh03jl12vd26h91.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHhf_zyia4mnUJ2q7GlUSjvAGR_wkayU',
    appId: '1:1009942668656:ios:320253a70c43e3a6b55bb5',
    messagingSenderId: '1009942668656',
    projectId: 'olopsc-thesis',
    storageBucket: 'olopsc-thesis.appspot.com',
    iosClientId: '1009942668656-pbip40b2nps7erhh2bh03jl12vd26h91.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
